[S12P21E206-80] Test: Jenkins 파이프라인 테스트

diff --git a/back/config/Dockerfile b/back/config/Dockerfile
--- a/back/config/Dockerfile
+++ b/back/config/Dockerfile
@@ -3,7 +3,7 @@ WORKDIR /app
 COPY gradlew gradlew.bat settings.gradle build.gradle ./
 COPY gradle/wrapper/gradle-wrapper.jar gradle/wrapper/gradle-wrapper.properties ./gradle/wrapper/
 RUN chmod +x gradlew
-RUN ./gradlew build --no-daemon
+RUN ./gradlew build --no-daemon || { echo 'Gradle build failed'; exit 1; }
 FROM openjdk:17-jdk-slim
 ARG JAR_FILE=build/libs/config-0.0.1-SNAPSHOT.jar
 COPY ${JAR_FILE} app.jar
